FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm config set proxy http://PlouseF:Uloserno888@10.14.160.53:3128
RUN npm config set https-proxy http://PlouseF:Uloserno888@10.14.160.53:3128
RUN npm install

COPY . .

CMD ["npm", "run", "start"]